---
# tasks file for reaper
- name: Install ntp
  yum:
    name: ntp

- name: Ensure ntp is started
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Ensure repo for reaper is present
  yum_repository:
    name: bintray-thelastpickle-reaper-rpm
    description: bintray-thelastpickle-reaper-rpm
    baseurl: https://dl.bintray.com/thelastpickle/reaper-rpm
    enabled: yes
    gpgcheck: no
  register: yum_repo

- name: Ensure epel is available
  yum:
    name: epel-release
    state: present
  register: epel

- name: Clear yum cache
  shell: yum clean all
  when: yum_repo.changed == True or epel.changed == True

- name: Add Cassandra Repository
  yum_repository:
    name: Cassandra
    description: Cassandra
    baseurl: "{{ cassandra_yum_repo_url }}"
    gpgcheck: 1
    gpgkey: "{{ cassandra_yum_repo_gpgkey_url }}"
    state: present

- name: Install additional packages
  yum:
    name: "{{ additional_packages }}"
    state: present

- name: Install Cassandra & Tools
  yum:
    name: "{{ cassandra_packages }}"
    state: present

- name: Set  authenticator in cassandra.yaml
  lineinfile:
    path: "/etc/cassandra/conf/cassandra.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { "regexp": "^authenticator:*", "line": "authenticator: PasswordAuthenticator" }
    - { "regexp": "^authorizer:*", "line": "authorizer: CassandraAuthorizer" }
    - { "regexp": "^cluster_name:*", "line": "cluster_name: Reaper" }
    - { "regexp": "^listen_address:*", "line": "listen_address: {{ ansible_eth1.ipv4.address }}" }
    - { "regexp": "^rpc_address:*", "line": "rpc_address: {{ ansible_eth1.ipv4.address }}" }
    - { "regexp": "^          - seeds: *", "line": "          - seeds: '192.168.43.201,192.168.43.202'" }
  register: config_change

- name: Restart cassandra service
  service:
    name: "cassandra"
    state: "restarted"
    enabled: "yes"
  when: config_change.changed == True

- name: Ensure C* is active
  wait_for:
    port: 9042
    host: "{{ ansible_eth1.ipv4.address }}"

- stat:
    path: /home/vagrant/cass_user.success
    get_checksum: no
  register: cass_user

- name: Create cql file to create C* admin user
  template:
    src: create_admin_user.cql.j2
    dest: /home/vagrant/create_admin_user.cql
  when: cass_user.stat.exists == False

- name: Run admin user script
  shell: cqlsh -u cassandra -p cassandra -f /home/vagrant/create_admin_user.cql && rm /home/vagrant/create_admin_user.cql && touch /home/vagrant/cass_user.success
  args:
    creates: /home/vagrant/cass_user.success
  environment:
    CQLSH_HOST: "{{ ansible_eth1.ipv4.address }}"

- name: Secure default cassandra user
  template:
    src: secure_default_cassandra_user.cql.j2
    dest: /home/vagrant/secure_default_cassandra_user.cql
  when: cass_user.stat.exists == False

- name: Run admin user script
  shell: cqlsh -u {{ cassandra_admin_user }} -p {{ cassandra_admin_user_pwd }} -f /home/vagrant/secure_default_cassandra_user.cql && rm /home/vagrant/secure_default_cassandra_user.cql && touch /home/vagrant/cass_user_secured.success
  args:
    creates: /home/vagrant/cass_user_secured.success
  environment:
    CQLSH_HOST: "{{ ansible_eth1.ipv4.address }}"
  run_once: yes

- name: Test that default cassandra user has been secured
  shell: cqlsh -u cassandra -p cassandra --execute "DESC KEYSPACES"
  register: cqlsh_output
  environment:
    CQLSH_HOST: "{{ ansible_eth1.ipv4.address }}"
  ignore_errors: yes
  run_once: yes

- assert:
    that:
      - "'Failed to authenticate' in cqlsh_output.stderr"

- stat:
    path: /home/vagrant/cass_reaper.success
    get_checksum: no
  register: cass_reaper

- name: Template reaper user script to host
  template:
    src: create_reaper_user.cql.j2
    dest: /home/vagrant/create_reaper_user.cql
  when: cass_reaper.stat.exists == False

- name: Ensure reaper keyspace exists
  cassandra_keyspace:
    login_user: "{{ cassandra_admin_user }}"
    login_password: "{{ cassandra_admin_user_pwd }}"
    login_host: "{{ ansible_eth1.ipv4.address }}"
    name: reaper_db
    state: present
    replication_factor: 2
  run_once: yes

- name: Copy reaper_schema.cql to host
  copy:
    src: "{{ item }}"
    dest: /home/vagrant
  with_glob:
    - files/cql7*.cql
  when: play_hosts.index(inventory_hostname) == 0

- name: Run reaper schema creation script TODO - Update to use new script
  shell: cqlsh -k reaper_db -u {{ cassandra_admin_user }} -p {{ cassandra_admin_user_pwd }} -f /home/vagrant/reaper_schema.cql && touch /home/vagrant/reaper_schema.cql.success
  args:
    creates:  /home/vagrant/reaper_schema.cql.success
  environment:
    CQLSH_HOST: "{{ ansible_eth1.ipv4.address }}"
  when: play_hosts.index(inventory_hostname) == 0

- name: Copy schema_migration_data.csv to host
  copy:
    src: schema_migration_data.csv
    dest: /home/vagrant/schema_migration_data.csv
  when: play_hosts.index(inventory_hostname) == 0

- name: Import data into schema_migration table
  shell: cqlsh -k reaper_db -u {{ cassandra_admin_user }} -p {{ cassandra_admin_user_pwd }} --execute "COPY schema_migration FROM '/home/vagrant/schema_migration_data.csv'" && touch /home/vagrant/schema_migration_data.csv.success
  args:
    creates: /home/vagrant/schema_migration_data.csv.success
  environment:
    CQLSH_HOST: "{{ ansible_eth1.ipv4.address }}"
  when: play_hosts.index(inventory_hostname) == 0

- name: Run reaper user script
  shell: cqlsh -u {{ cassandra_admin_user }} -p {{ cassandra_admin_user_pwd }} -f /home/vagrant/create_reaper_user.cql && rm /home/vagrant/create_reaper_user.cql && touch /home/vagrant/cass_reaper.success
  args:
    creates: /home/vagrant/cass_reaper.success
  environment:
    CQLSH_HOST: "{{ ansible_eth1.ipv4.address }}"
  when: play_hosts.index(inventory_hostname) == 0

- name: Ensure Reaper repo is available
  yum_repository:
    name: bintray-thelastpickle-reaper-rpm
    description: bintray-thelastpickle-reaper-rpm
    baseurl: https://dl.bintray.com/thelastpickle/reaper-rpm
    gpgcheck: no
    repo_gpgcheck: no
    enabled: yes

- name: Ensure reaper is installed
  yum:
    name: "{{ reaper_package }}"
    state: installed

- name: Remove st memory
  lineinfile:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    line: "storageType: memory"
    state: absent

- name: Ensure datetime is in log file
  lineinfile:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    regexp: '^      logFormat:.*'
    insertafter: '.*type: file.*'
    line: '      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"'

- name:
  blockinfile:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    block: |
      storageType: cassandra
      cassandra:
        clusterName: "Reaper"
        contactPoints: ["{{ ansible_eth1.ipv4.address }}"]
        keyspace: reaper_db
        queryOptions:
          consistencyLevel: LOCAL_ONE
          serialConsistencyLevel: SERIAL
        authProvider:
          type: plainText
          username: {{ cassandra_reaper_user }}
          password: {{ cassandra_reaper_user_pwd }}

- name: Start reaper on the first server only
  service:
    name: cassandra-reaper
    state: started
    enabled: yes
  register: first_start
  when: play_hosts.index(inventory_hostname) == 0

- name: Wait for schema to sync between nodes on first start
  wait_for:
    path: /var/log/messages
    search_regex: "Migration of repair_unit and repair_schedule tables completed"
  when:
    - play_hosts.index(inventory_hostname) == 0
    - first_start.changed == True

- pause:
    seconds: 10
  when: first_start.changed == True

- name:  Start reaper on the remaining servers
  service:
    name: cassandra-reaper
    state: started
    enabled: yes
  when: play_hosts.index(inventory_hostname) > 0

- name: Ensure Cassandra Reaper always starts after C*
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/cassandra-reaper.service
    regexp: '^After=remote-fs.target syslog.socket$'
    line: 'After=remote-fs.target syslog.socket cassandra.service'
  register: systemd_reload

- name: Delay start of Cassandra Reaper
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/cassandra-reaper.service
    line: 'Type=idle'
    insertafter: '^ExecStart*'
  register: systemd_type_reload

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes
  when: systemd_reload.changed == True or systemd_type_reload.changed == True

- name: Restart reaper
  service:
    name: cassandra-reaper
    state: restarted
  when: systemd_reload.changed == True
